#Battle results
BATTLE_UNDECIDED = 0
BATTLE_LOST = 1
BATTLE_WON = 2
TIMED_OUT = 3
OPPONENT_TIMED_OUT = 4

#Targetability options
SELF = 0
MELEE = 1
RANGED = 2
FRIENDLY = 3
FRIENDLY_NONSELF = 4
RANDOM_ENEMY = 5

#Maximum skill number
MAX_SKILL_NUM = 15

#Effect IDs
EFFECT_BLINDED = 0
EFFECT_DEFENSIVE_POSTURE = 1
EFFECT_COVER = 2
EFFECT_PROTECTED = 3
EFFECT_SHIELD_WALL = 4

#Ranged targetability penalties
NO_PENALTY = 0
SLIGHT_PENALTY = 1
SEVERE_PENALTY = 2

#Skills
SKILL_STRIKE = 0
SKILL_THROWN = 1
SKILL_RETREAT = 2
SKILL_DIRT = 3
SKILL_DEFENSIVE_POSTURE = 4
SKILL_COVER = 5
SKILL_QUICK_STRIKE = 6
SKILL_HEAVY_STRIKE = 7
SKILL_ACCURATE_STRIKE = 8
SKILL_FINISHING_STRIKE = 9
SKILL_PROTECT = 10
SKILL_SHIELD_WALL = 11
SKILL_COUNTERSTRIKE = 12
SKILL_FLING = 13
SKILL_QUICK_THROW = 14
SKILL_HEAVY_THROW = 15

