#Battle results
BATTLE_UNDECIDED = 0
BATTLE_LOST = 1
BATTLE_WON = 2
TIMED_OUT = 3
OPPONENT_TIMED_OUT = 4

#Targetability options
SELF = 0
MELEE = 1
RANGED = 2
FRIENDLY = 3
FRIENDLY_NONSELF = 4
RANDOM_ENEMY = 5

#Maximum skill number
MAX_SKILL_NUM = 22

#Effect IDs
EFFECT_BLINDED = 0
EFFECT_DEFENSIVE_POSTURE = 1
EFFECT_COVER = 2
EFFECT_PROTECTED = 3
EFFECT_SHIELD_WALL = 4
EFFECT_TAKEN_AIM = 5
EFFECT_UNDISTURBED = 6
EFFECT_STUNNED = 7
EFFECT_MIND_POISON = 8
EFFECT_PARALYZING_POISON = 9
EFFECT_WEAKNESS_POISON = 10
EFFECT_APPLIED_MIND_POISON = 11
EFFECT_APPLIED_PARALYZING_POISON = 12
EFFECT_APPLIED_WEAKNESS_POISON = 13
EFFECT_BLEEDING = 14
EFFECT_RAN_UP = 15


#Ranged targetability penalties
NO_PENALTY = 0
SLIGHT_PENALTY = 1
SEVERE_PENALTY = 2

#Disciplines, negative to separate from skills
DISCIPLINE_NONE = -1
DISCIPLINE_MELEE_COMBAT = -2
DISCIPLINE_RANGED_COMBAT = -3
DISCIPLINE_DIRTY_COMBAT = -4

#Skills
SKILL_STRIKE = 0
SKILL_THROWN = 1
SKILL_RETREAT = 2
SKILL_DIRT = 3
SKILL_DEFENSIVE_POSTURE = 4
SKILL_COVER = 5
SKILL_QUICK_STRIKE = 6
SKILL_HEAVY_STRIKE = 7
SKILL_ACCURATE_STRIKE = 8
SKILL_FINISHING_STRIKE = 9
SKILL_PROTECT = 10
SKILL_SHIELD_WALL = 11
SKILL_COUNTERSTRIKE = 12
SKILL_FLING = 13
SKILL_QUICK_THROW = 14
SKILL_HEAVY_THROW = 15
SKILL_TAKE_AIM = 16
SKILL_UNDISTURBED = 17
SKILL_BOLA = 18
SKILL_MIND_POISON = 19
SKILL_PARALYZING_POISON = 20
SKILL_WEAKNESS_POISON = 21
SKILL_RUN_UP = 22

#Equipment Types
EQUIPMENT_SWORD = 0
EQUIPMENT_MACE = 1
EQUIPMENT_AXE = 2
EQUIPMENT_SPEAR = 3
EQUIPMENT_THROWING_KNIVES = 4
EQUIPMENT_JAVELINS = 5
EQUIPMENT_THROWING_AXES = 6
EQUIPMENT_SHIELD = 7
EQUIPMENT_HEAD = 8
EQUIPMENT_CHEST = 9
EQUIPMENT_LEGS = 10

INITIAL_CHAR_POINTS = 20

